
WITH CUSTOMERORDERS AS (
    SELECT C.CUSTOMERID, CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME, COUNT(O.ORDERID) AS NO_OF_ORDERS
    FROM L1_LANDING.CUSTOMERS C
    JOIN L1_LANDING.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY NO_OF_ORDERS
)

SELECT CUSTOMERID, CUSTOMERNAME, NO_OF_ORDERS
FROM CUSTOMERORDERS