sources:
  - name: ClimberRecruitments
    database: recruitments
    schema: public
    tables:
      - name: areas
      - name: persons
      - name: attempts
      - name: events
      - name: titles
      - name: types
      - name: statuses
models:
    - name: Events_1
      columns:
          - name: person
          - name: person_date
          - name: person_date_status
          - name: attempt
          - name: attemps_events
          - name: status_group
          - name: status_overall
          - name: status
          - name: status_waterfall
          - name: date
          - name: information